In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

import numpy as np
import pandas as pd

import OU_model_generator

In [2]:
np.random.uniform(low=0, high=1, size=3)

array([0.20898459, 0.54374931, 0.06269357])

In [3]:
OU_model_generator.simulate_OU(10, 1, 1.2, 0, 1.5, 0, False)[2]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [4]:
OU_processes = np.array([OU_model_generator.simulate_OU(10, 1, 1.2, 0, 1.5, 0, False)[1]])

for i in range(3):
    OU_processes = np.append(OU_processes, np.array([OU_model_generator.simulate_OU(10, 1, 1.2, 0, 1.5, 0, False)[1]]), axis=0)
#print(OU_processes)
print(OU_processes.T)


[[ 0.          0.          0.          0.        ]
 [-0.52468071 -0.0945351  -0.16050636  0.90955986]
 [-0.24255843  0.22652238  0.11878039  0.45370924]
 [-0.003283   -0.47644445  0.20754773  0.63220998]
 [ 0.39061112 -0.81517045  0.54964563  0.99292862]
 [ 0.25411193 -0.38277057  0.45454964  0.96039861]
 [-0.24264069  0.23798435 -0.17133886  1.27752901]
 [-0.05549945 -0.04014262 -0.51937345  1.50658819]
 [ 0.08083382 -0.27713919 -0.34714091  1.54605653]
 [-0.27848184 -0.74930911 -0.04789219  1.64284001]
 [-0.24699124 -0.66457756 -0.04247657  1.45706838]]


In [5]:
np.random.uniform(low=0, high=1, size=8).reshape(8, 1)

array([[0.22087119],
       [0.15632506],
       [0.19817485],
       [0.26194665],
       [0.82299595],
       [0.29330209],
       [0.50626277],
       [0.53018508]])

In [6]:
np.array([[input_data] for input_data in OU_processes.T[10]])

array([[-0.24699124],
       [-0.66457756],
       [-0.04247657],
       [ 1.45706838]])

In [7]:
for i in range(1,100):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
